# Generated by Django 3.0.6 on 2020-06-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200618_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default=1592469515.998306, max_length=200),
        ),
    ]
